In [2]:
import numpy as np
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
mydict

{'a': 0,
 'b': 1,
 'c': 2,
 'e': 3,
 'd': 4,
 'f': 5,
 'g': 6,
 'h': 7,
 'i': 8,
 'j': 9,
 'k': 10,
 'l': 11,
 'm': 12,
 'n': 13,
 'o': 14,
 'p': 15,
 'q': 16,
 'r': 17,
 's': 18,
 't': 19,
 'u': 20,
 'v': 21,
 'w': 22,
 'x': 23,
 'y': 24,
 'z': 25}

In [6]:
!pip install pandas 
import pandas as pd

Requirement already satisfied: pandas in c:\users\sainath reddy\appdata\local\programs\python\python311\lib\site-packages (1.5.3)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\sainath reddy\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\sainath reddy\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2023.2)
Requirement already satisfied: numpy>=1.21.0 in c:\users\sainath reddy\appdata\local\programs\python\python311\lib\site-packages (from pandas) (1.24.2)
Requirement already satisfied: six>=1.5 in c:\users\sainath reddy\appdata\local\programs\python\python311\lib\site-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)

ValueError: If using all scalar values, you must pass an index

In [22]:
x1=pd.Series(mydict)
r1=pd.Series(mylist)
r2=pd.Series(myarr)
x2=pd.concat([r1,r2],axis=1)
x2=pd.DataFrame({'index':r1,'number':r2})
x2

   index  number
0      a       0
1      b       1
2      c       2
3      e       3
4      d       4
5      f       5
6      g       6
7      h       7
8      i       8
9      j       9
10     k      10
11     l      11
12     m      12
13     n      13
14     o      14
15     p      15
16     q      16
17     r      17
18     s      18
19     t      19
20     u      20
21     v      21
22     w      22
23     x      23
24     y      24
25     z      25

In [32]:
x=pd.Series(list('abcedfghijklmnopqrstuvwxyz'))
# r=pd.DataFrame(x)
c=pd.DataFrame({'index':x})
c

   index
0      a
1      b
2      c
3      e
4      d
5      f
6      g
7      h
8      i
9      j
10     k
11     l
12     m
13     n
14     o
15     p
16     q
17     r
18     s
19     t
20     u
21     v
22     w
23     x
24     y
25     z

In [43]:
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])